//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emprestimoweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emprestimo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Emprestimo()
        {
            this.ItensEmprestimo = new HashSet<ItensEmprestimo>();
        }
    
        public int Codigo { get; set; }
        public Nullable<int> Aluno { get; set; }
        public Nullable<System.DateTime> Data_Emprestimo { get; set; }
        public Nullable<System.DateTime> Data_Devolucao { get; set; }
    
        public virtual Aluno Aluno1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItensEmprestimo> ItensEmprestimo { get; set; }
    }
}
