//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emprestimoweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItensEmprestimo
    {
        public int Id { get; set; }
        public Nullable<int> EmprestimoCod { get; set; }
        public Nullable<int> LivroCod { get; set; }
    
        public virtual Emprestimo Emprestimo { get; set; }
        public virtual Livro Livro { get; set; }
    }
}
