//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emprestimoweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Livro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Livro()
        {
            this.ItensEmprestimo = new HashSet<ItensEmprestimo>();
        }
    
        public int Codigo { get; set; }
        public Nullable<int> Autor { get; set; }
        public Nullable<int> Editora { get; set; }
        public string ISBN { get; set; }
        public string Titulo { get; set; }
    
        public virtual Autor Autor1 { get; set; }
        public virtual Editora Editora1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItensEmprestimo> ItensEmprestimo { get; set; }
    }
}
